const dinosauresList = [
  {
    name: "Allosaurus",
    surname: "Alexendre",
    description:
      "Le dinosaure Allosaurus (Allosaure) est un énorme Carnosaure, l un des plus grands de la famille des Allosauridés, il était probablement le plus féroce prédateur du Jurassique.",
    image: "src/Dinosaures/allosaurus.jpeg",
    diet: "carnivore",
    attribut: "terrestre",
  },
  {
    name: "T-rex",
    surname: "Benoît",
    description: "",
    image: "src/Dinosaures/t-rex.jpeg",
    diet: "carnivore",
    attribut: "terrestre",
  },
  {
    name: "Ankylosaurus",
    surname: "Alexis",
    description: "",
    image: "src/Dinosaures/ankylosaurus.png",
    diet: "herbivore",
    attribut: "terrestre",
  },
  {
    name: "Anhanguera",
    surname: "Alhassane",
    description: "",
    image: "src/Dinosaures/anhanguera.jpg",
    diet: "carnivore",
    attribut: "volant",
  },
  {
    name: "Cératosaurus",
    surname: "Calypso",
    description: "",
    image: "src/Dinosaures/Ceratosaurus.jpeg",
    diet: "carnivore",
    attribut: "terrestre)",
  },
  {
    name: "Cryptoclidus",
    surname: "Cedric",
    description: "",
    image: "src/Dinosaures/cryptoclidus.png",
    diet: "herbivore",
    attribut: "aquatique",
  },
  {
    name: "Centrosaure",
    surname: "Charles",
    description: "",
    image: "src/Dinosaures/Centrosaurus.png",
    diet: "herbivore",
    attribut: "terrestre",
  },
  {
    name: "Dimorphodon",
    surname: "Didier",
    description: "",
    image: "",
    diet: "carnivore",
    attribut: "volant",
  },
  {
    name: "Fabrosaurus",
    surname: "Frédéric",
    description: "",
    image: "src/Dinosaures/fabrosaurus.png",
    diet: "herbivore",
    attribut: "terrestre",
  },
  {
    name: "Jainosaurus",
    surname: "Jean-Louis",
    description: "",
    image: "src/Dinosaures/Jainosaurus.png",
    diet: "herbivore",
    attribut: "terrestre",
  },
  {
    name: "Jobaria",
    surname: "Jordan",
    description: "",
    image: "src/Dinosaures/jobaria.png",
    diet: "herbivore",
    attribut: "terrestre",
  },
  {
    name: "Kronosaurus",
    surname: "Kevin",
    description: "",
    image: "src/Dinosaures/Kronosaurus.png",
    diet: "carnivore",
    attribut: "aquatique",
  },
  {
    name: "Mosasaurus",
    surname: "Maxence",
    description: "",
    image: "src/Dinosaures/mosasaurus.png",
    diet: "carnivore",
    attribut: "aquatique",
  },
  {
    name: "Spinosaure",
    surname: "Nelson",
    description: "",
    image: "src/Dinosaures/Spinosaurus.png",
    diet: "carnivore",
    attribut: "terrestre",
  },
  {
    name: "Espèce éteinte",
    surname: "Nicolas",
    description: "",
    image: "src/Dinosaures/squelette_de_dinosaure.png",
    diet: "herbivore",
    attribut: "terrestre",
  },
  {
    name: "Protocératops",
    surname: "Paul",
    description: "",
    image: "src/Dinosaures/Protoceratops.jpg",
    diet: "herbivore",
    attribut: "terrestre",
  },
  {
    name: "Ptéranodon",
    surname: "Prasanna",
    description: "",
    image: "src/Dinosaures/Pteranodon.jpg",
    diet: "carnivore",
    attribut: "volant",
  },
  {
    name: "Stegosaurus",
    surname: "Sandrine",
    description: "",
    image: "src/Dinosaures/stegosaure.png",
    diet: "herbivore",
    attribut: "terrestre",
  },
  {
    name: "Stenopterygius",
    surname: "Suzy",
    description: "",
    image: "",
    diet: "carnivore",
    attribut: "aquatique",
  },
  {
    name: "Vélociraptor",
    surname: "Valentin",
    description: "",
    image: "",
    diet: "carnivore",
    attribut: "terrestre",
  },
  {
    name: "Xiaosaurus",
    surname: "Xavier",
    description: "",
    image: "",
    diet: "herbivore",
    attribut: "terrestre",
  },
];
export default dinosauresList;
